{% set name = "safety" %}
{% set version = "1.10.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2ab09596ebcbb4012fb7345d2dbda28319c8f3c2731ef6e27ba206b279c13b2

build:
  number: 0
  entry_points:
    - safety=safety.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - click >=6.0
    - dparse >=0.5.1
    - packaging
    - python >=3.5
    - requests
    - setuptools

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - safety
  commands:
    - pip check
    - safety --help
    - pytest

about:
  home: https://pyup.io/safety
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  doc_url: https://pyup.io/docs
  dev_url: https://github.com/pyupio/safety

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
