{% set version = "2.2.0" %}

package:
  name: safety
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/safety/safety-{{ version }}.tar.gz
  sha256: 6745de12acbd60a58001fe66cb540355187d7b991b30104d9ef14ff4e4826073

build:
  number: 0
  entry_points:
    - safety=safety.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=8.0.2
    - dparse >=0.5.1
    - packaging >=21.0
    - python >=3.6
    - requests
    - ruamel.yaml >=0.17.21
    - setuptools >=19.3

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - git
  imports:
    - safety
  commands:
    - pip check
    - safety --help
    - safety --version
    - pytest

about:
  home: https://pyup.io/safety
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  doc_url: https://pyup.io/docs
  dev_url: https://github.com/pyupio/safety

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
