{% set version = "2.3.1" %}

package:
  name: safety
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/safety/safety-{{ version }}.tar.gz
  sha256: 6e6fcb7d4e8321098cf289f59b65051cafd3467f089c6e57c9f894ae32c23b71

build:
  number: 0
  entry_points:
    - safety=safety.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=8.0.2
    - dparse >=0.6.2
    - packaging >=21.0
    - python >=3.6
    - requests
    - ruamel.yaml >=0.17.21
    - setuptools >=19.3

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - git
  imports:
    - safety
  commands:
    - pip check
    - safety --help
    - safety --version
    - pytest

about:
  home: https://pyup.io/safety
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  doc_url: https://pyup.io/docs
  dev_url: https://github.com/pyupio/safety

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
