travis:
  secure:
    BINSTAR_TOKEN: URGUpA+m3dT1NdqQml5UbUppaQFBZl8W0wx0g8Jk6Vlwdr5gXJekmF2gBs1Fdy4GRW1+AGwx1FOHakWIZY/guw/k7AHwpweAZIs9LhNsA1PhMViIPZGLzNS4+CcL9FSBjHyZD2u4j3TDPcKsB/c9PE2Gx6BSy1nRrTK2s4S3mKW/FDon46pibsIeO7FZsJuaKW4KuJeItV59/PBvYglae0BD2Z5RARD0e4y16wty6mmgrvV5OBHxqgdwEUkakKFjma0bA0kyRAuWGYfCmbT7dbprbtG4mPa1ImlcDUXqXA9O0BY5Y5r7JFiJiUS/UwD5WS5Ij6IQy8PQg3TQJDrfDUQNeiZzIjNSsomOmL4BlP0BvoPi6cDwZeYLBSubdr1td6hQiN602RsqHjnxy0++htCkWYHV4G3PEhLcrffrdit7bvnY5t7yYck6NUmm7I4kNHVZZd5zdn7LQZzQi1LVR7O+a/9jNNn63MeVHBc0H4wUftRO8NWVonc9Ilzf1cbPcoTU8WL01aZXZeaM559wL31/w+fnSLX/uJa5pHKRMdZKP/59t9TKpZMhD3kB1/Wbgw39CDKELuDnmndAM8nnaSqHSQuvUTRMq+0/gMP2mgTYyQlZ+Fd8A1gSarquEr1nzgo0Ae9hyi6irsixtbZw5w30NYnMur6SMLlad3ajcNo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
